c      
      SUBROUTINE GSCALE
c
c     SCALE VELOCITIES FOR DESIRED TEMPERATURE DURING EQUILIBRATION IF LSCALE .TRUE. IN MDINPUT.DAT
c
c     ATTENTION!!! THE ACTUAL KINETIC ENERGY IS CALCULATED FROM THE VELOCITIES AT STEP N
c                  THE VELOCITIES SCALED ARE THOSE AT STEP N+1/2 USED IN THE NEXT Verlet "LEAP-FROG" MD TIME-STEP
c
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
c
      PARAMETER(NCOMPMAX=5)
      PARAMETER(NMOLMAX=256)
      PARAMETER(NSPECMAX=10)
      PARAMETER(NATSPMAX=100)    
c                                               
      COMMON/INTGRS/IN(14)
      COMMON/REALS /RL(18)     
c      
      COMMON/VELOC /VX(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              VY(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              VZ(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX)              
      COMMON/PARMOL/NMOL(NMOLMAX),NSPEC(NSPECMAX),
     &NATMSP(NCOMPMAX,NATSPMAX)
c
      EQUIVALENCE (IN(1),NCOMP)
      EQUIVALENCE (RL(5),TKECONV),(RL(6),ACTKE),(RL(7),DTEMP)
c
c     CALCULATE VELOCITY SCALING FACTOR FOR DESIRED TEMPERATURE - Haile, J.M., 1992
c     
c     SCALING FACTOR = SQUARE ROOT(DESIRED TEMPERATURE/ACTUAL TEMPERATURE)
c     TSCFAC         = SQRT(DTEMP/ATEMP)
c
      TSCFAC = DSQRT(DTEMP/(ACTKE*TKECONV))
*     TSCFAC = (DTEMP/(ACTKE*TKECONV))**(1.0D0/2.0D0)
c      
      DO 5 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 15 J=1,JMAX 
            DO 25 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 35 L = 1,LMAX
                  VX(I,J,K,L) = VX(I,J,K,L)*TSCFAC
                  VY(I,J,K,L) = VY(I,J,K,L)*TSCFAC
                  VZ(I,J,K,L) = VZ(I,J,K,L)*TSCFAC
   35          CONTINUE
   25       CONTINUE      
   15    CONTINUE
    5 CONTINUE
c
      RETURN
      END 
c
c
c