c      
      SUBROUTINE MDVEL
c
c     ASSIGN RANDOM VELOCITIES [Bohr/atu] FOR ALL ATOMS USING THE FUNCTION RANF(DUMMY) FROM Allen and Tildesley, 1997
c     SCALE VELOCITIES FOR ZERO TOTAL LINEAR MOMENTUM AND FOR DESIRED TEMPERATURE BY CALLING GSCALE
c
c     ATTENTION!!! THE VELOCITIES OF THE ATOMS OF A MOLECULE ARE ASSIGNED WITH THE SAME RANDOM NUMBER BETWEEN 0 AND 1
c                  SCALING FOR ZERO TOTAL LINEAR MOMENTUM CAUSES THE ATOMIC VELOCITIES TO DIFFER DEPENDING ON THE ATTOMIC MASS
c     ATTENTION!!! THIS ROUTINE IS CALLED ONLY ONE TIME IF LVEL IS DEFINED AS .TRUE. IN THE INPUT FILE mdcontrl.dat
c                  FOR THE VERLET "LEAP-FROG" ALGORITHM THE VELOCITIES DEFINED IN THIS ROUTINE ARE THE VELOCITIES AT STEP -1/2
c
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
c
      PARAMETER(NCOMPMAX=5)
      PARAMETER(NMOLMAX=256)
      PARAMETER(NSPECMAX=10)
      PARAMETER(NATSPMAX=100)    
c                                               
      COMMON/INTGRS/IN(14)
      COMMON/REALS /RL(18)     
c      
      COMMON/VELOC /VX(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              VY(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              VZ(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX)              
      COMMON/PARMOL/NMOL(NMOLMAX),NSPEC(NSPECMAX),
     &NATMSP(NCOMPMAX,NATSPMAX)
      COMMON/ATMASS/ZMASS(NCOMPMAX,NSPECMAX,NATSPMAX)
c...  Store random velocities for every molecule of every component      
      DIMENSION RANDVX(NCOMPMAX,NMOLMAX),RANDVY(NCOMPMAX,NMOLMAX),
     &RANDVZ(NCOMPMAX,NMOLMAX)
c
      EQUIVALENCE (IN(1),NCOMP)
      EQUIVALENCE (RL(6),ACTKE),(RL(11),FNATOMS)
c
c     ASSIGN RANDOM VELOCITY COMPONENTS [0,1] TO EVERY MOLECULE OF EVERY COMPONENT
c
      DO 5 I = 1,NCOMP
         JMAX = NMOL(I)
         DO 15 J=1,JMAX 
            RANDVX(I,J)=RANF(DUMMY)
            RANDVY(I,J)=RANF(DUMMY)  
            RANDVZ(I,J)=RANF(DUMMY)     
   15    CONTINUE
    5 CONTINUE   
c    
c     ASSIGN EQUAL VELOCITIES TO ALL THE ATOMS OF EVERY MOLECULE OF EVERY COMPONENT
c     CALCULATE THE TOTAL LINEAR MOMENTUM TO CORRECT VELOCITIES FOR ZERO TOTAL LINEAR MOMENTUM
c
      PX   = 0.0D0
      PY   = 0.0D0
      PZ   = 0.0D0
c      
      DO 25 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 35 J=1,JMAX 
            DO 45 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 55 L = 1,LMAX
                  VX(I,J,K,L) = RANDVX(I,J) 
                  VY(I,J,K,L) = RANDVY(I,J)
                  VZ(I,J,K,L) = RANDVZ(I,J)
                  PX = PX + ZMASS(I,K,L)*VX(I,J,K,L)
                  PY = PY + ZMASS(I,K,L)*VY(I,J,K,L)
                  PZ = PZ + ZMASS(I,K,L)*VZ(I,J,K,L) 
   55          CONTINUE
   45       CONTINUE      
   35    CONTINUE
   25 CONTINUE
c
c     SCALE VELOCITY COMPONENTS FOR ZERO TOTAL LINEAR MOMENTUM
c
      DO 65 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 75 J=1,JMAX 
            DO 85 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 95 L = 1,LMAX
                  VX(I,J,K,L) = VX(I,J,K,L)-PX/(ZMASS(I,K,L)*FNATOMS) 
                  VY(I,J,K,L) = VY(I,J,K,L)-PY/(ZMASS(I,K,L)*FNATOMS) 
                  VZ(I,J,K,L) = VZ(I,J,K,L)-PZ/(ZMASS(I,K,L)*FNATOMS) 
   95          CONTINUE
   85       CONTINUE      
   75    CONTINUE
   65 CONTINUE
c
c     SCALE VELOCITIES AT STEP -1/2 FOR DESIRED TEMPERATURE
c     CALCULATE ACTUAL KINETIC ENERGY TO SCALE VELOCITIES FOR DESIRED TEMPERATURE IN SUBROUTINE GSCALE 
c
      DO 105 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 115 J=1,JMAX 
            DO 125 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 135 L = 1,LMAX
                  ACTKE=ACTKE+0.5D0*ZMASS(I,K,L)*
     &(VX(I,J,K,L)**2.0D0+VY(I,J,K,L)**2.0D0+VZ(I,J,K,L)**2.0D0) 
  135          CONTINUE
  125       CONTINUE      
  115    CONTINUE
  105 CONTINUE
c     
      CALL GSCALE
c
c     WRITE HEAD OF THE FILE MDVELT.DAT
c
      WRITE(4,'((7X,A12),2(12X,A12))')'VX(Bohr/aut)','VY(Bohr/aut)',
     &'VZ(Bohr/aut)'
c
c     WRITE INITIAL VELOCITIES TO FILE MDVELT.DAT - FREE FORMAT
c
      DO 145 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 155 J=1,JMAX 
            DO 165 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 175 L = 1,LMAX
                  WRITE(4,*)VX(I,J,K,L),VY(I,J,K,L),VZ(I,J,K,L)   
  175          CONTINUE
  165       CONTINUE      
  155    CONTINUE
  145 CONTINUE
c     
      RETURN
      END 
c
c
c