c
      SUBROUTINE MDVISUAL
c
c     CAREFULL!!! PDB FORMAT INCOMPLETE FOR THE CASE OF POLYATOMIC MOLECULES 
c                 THE COMMAND CONECT IS NOT WRITTEN BUT VMD STILL CONNECTS ATOMS FOR SIMPLE MOLECULES
c
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
c
      PARAMETER(NCOMPMAX=5)
      PARAMETER(NMOLMAX=256)
      PARAMETER(NSPECMAX=10)
      PARAMETER(NATSPMAX=100)
      PARAMETER(NPARTCL=500)
c      
      PARAMETER(BANG=0.5291772083D0)      
c
      CHARACTER*4  NAMEAT
c      
      COMMON/INTGRS/IN(14)
c      
      COMMON/POSIT /RX(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              RY(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX),
     &              RZ(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX)
      COMMON/POSSD /XX(NPARTCL),YY(NPARTCL),ZZ(NPARTCL)
      COMMON/PARMOL/NMOL(NMOLMAX),NSPEC(NSPECMAX),
     &NATMSP(NCOMPMAX,NATSPMAX)
      COMMON/ATNAME/NAMEAT(NCOMPMAX,NSPECMAX,NATSPMAX)
      COMMON/ATNUMB/NUMBAT(NCOMPMAX,NMOLMAX,NSPECMAX,NATSPMAX)   
c  
      EQUIVALENCE (IN(1),NCOMP),(IN(3),NATOMS),(IN(4),NATOMS1)
c 
c     ATTENTION!!! PDB (Protein Data Bank) FILES ARE WRITTEN IN ANGSTROMS
c     
      WRITE(9,'(I4)')NATOMS
      WRITE(9,*)'MD trajectory step'
      DO 5 I = 1,NCOMP
         JMAX = NMOL(I)
         KMAX = NSPEC(I)
         DO 15 J=1,JMAX 
            DO 25 K = 1,KMAX
               LMAX = NATMSP(I,K)
               DO 35 L = 1,LMAX
                  RAX=RX(I,J,K,L)*BANG
                  RAY=RY(I,J,K,L)*BANG
                  RAZ=RZ(I,J,K,L)*BANG
      WRITE(8,'(A4,2X,I5,1X,A4,1X,A3,2X,I4,4X,F8.3,F8.3,F8.3,F6.2,F6.2)
     &')'ATOM',NUMBAT(I,J,K,L),NAMEAT(I,K,L),'RES',1,RAX,RAY,RAZ,1.00,
     &0.00
      WRITE(9,'(1X,A3,3X,3(F11.4,2X))')NAMEAT(I,K,L),RAX,RAY,RAZ
   35          CONTINUE
   25       CONTINUE      
   15    CONTINUE
    5 CONTINUE      
c
      WRITE(8,*)'                                                     '
      RETURN
      END
c
c
c      